site_name: PyMAAP
site_url: https://sralter.github.io/pymaap
repo_url: https://github.com/sralter/pymaap
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
plugins:
  - search

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference: reference.md